manifestspecific.py

CP-10514: Watch RDP status in Windows PV tool
CP-10490: puncture firewall when enabling RDP

XenGuestAgent #126

---

manifestspecific.py

CP-10953: Windows guest agent: announce feature-ts cheng.zhang

XenGuestAgent #127:

---

src/drivers/citrixxendrivers.wxs

Old drivers msis can accidentally remove them

[CA-159427] Save guestagent reg entries & reinstate them after install

---

manifestspecific.py

[CA-156206] byte count string communications between dpriv & guest agent

XenGuestAgent #128

---

manifestspecific.py

[CA-156206] byte count string communications between dpriv & guest agent

xenguestagent # 128

---

src/drivers/drivers.wxs

[CP-10562] Add xendisk.sys to drivers msi

---

manifestspecific.py

CA-160190: Windows guests firewall exception force change

xenguestagent #130

---

build.py
src/agent/citrixguestagent.wxs

Force add/remove exception for RDP, we need to add such dll for COM interface.
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

CA-160190: add Interop.NetFwTypeLib.dll

---

manifestspecific.py

[CP-11175] Report presence of XenDesktop VDA on Guest into xenstore

xenguestagent.git 131

---

src/installwizard/InstallWizard/InstallService.cs
src/installwizard/InstallWizard/Support.cs

This reverts commit 3361274a3d062897b8a54c89938982c1b44f5f7b.
Conflicts:
manifestspecific.py

Revert "Revert to d39e09ff8dd9181fd4a17e6f46159bfc7524942e"

---

manifestspecific.py

CA-167374 : read the byte count when communicating between agent and dpriv

xenguestagent #132

---

manifestspecific.py

Coinstaller does not fail if network settings fail to copy

[Win10] Update Xennet 7.2.0.17

---

manifestspecific.py

Update to XenBus 7.2.0.51 (WHQL)

---

manifestspecific.py

Test: xenvbd 15 (target-list)

---

src/drivers/citrixxendrivers.wxs
src/installwizard/InstallWizard/InstallService.cs
src/installwizard/InstallWizard/Support.cs

Creamtake1

---

manifestspecific.py

[CA-168019] Release and re-acquire backend on resume

xenvif-patchq 8.0 #14

---

manifestspecific.py

StorPortNotification(BusChanged)

Force IoInvalidateDeviceRelations(BusRelations) as well as

---

manifestspecific.py

Update to xenvbd #18

---

manifestspecific.py
src/drivers/drivers.wxs

Update to xenvbd #19 (remove xendisk)

---

manifestspecific.py

Add XenDisk back and apply fixes from Amazon

Update to XenVbd #20

---

src/drivers/drivers.wxs

Re-add xendisk to driver msi

---

manifestspecific.py

CP-11966 : Execute batch scripts via xenstore interface

XenGuestAgent #133

---

manifestspecific.py

AddPatch: Account for rewinding requests

Xenvif-patchq #93

---

manifestspecific.py

CP-12665 : Add per-guest vm registry entry to prevent remote execution

XenGuestAgent #134

---

manifestspecific.py
src/drivers/drivers.wxs

Remove XenDisk

---

manifestspecific.py

XenVbd #97

---

manifestspecific.py

Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

CA-177487: Add dependency of CryptSvc to guest agent

---

manifestspecific.py

Update to 8.1 drivers

---

manifestspecific.py

Update to Win10-WHQLed drivers

---

build.py

Update TOOLS_HOTFIX_NUMBER to 20200

---

build.py
proj/XenPrep.sln
src/xenprep/Progress.Designer.cs
src/xenprep/Progress.cs
src/xenprep/Progress.resx
src/xenprep/XenPrep.cs
src/xenprep/XenPrepSupport.cs
src/xenprep/Xenprep.csproj

Cp 13459 - Install new guest agent from xenprep

---

build.py
proj/XenPrep.sln
src/xenprep/Progress.Designer.cs
src/xenprep/Progress.cs
src/xenprep/Progress.resx
src/xenprep/XenPrep.cs
src/xenprep/XenPrepSupport.cs
src/xenprep/Xenprep.csproj

Reverts xenserver/win-installer#194
Return xenserver/win-installer#193

Revert "Revert "Initial commit of XenPrep Project""

---

manifestspecific.py

1. CP-13694: Add automatic self-update to .net guest (detail)
2. CP-13694: change default autoupdate URL to 127.0.0.1 (detail)
3. CP-13693: Automatic guest agent updating a licensed feature (detail)

xenguestagent #138

---

manifestspecific.py

CP-13380 : Guest agent copies network settings to store / emulated devices — Ben.Chalmers

xenguestagent #139

---

src/xenprep/XenPrepSupport.cs

Uninstall VSS, Guest Agent, PV Drivers and the Tools Installer
using their MSI uninstallers.

CP-13461: Run MSI uninstallers

---

src/xenprep/XenPrepSupport.cs

- Set the 'len' variable to BUF_LEN in every iteration. The value gets
overwritten with the returned string's length with every call to
MsiGetProductInfo().
- Remove the '/norestart' flag when uninstalling XenServer Tools Installer
(if the flag exists, the Installer doesn't get uninstalled)
- Keep a hash table of product codes/names to be removed, and remove them
after finishing iterating through all products. If 2 products are
adjacent, the second one is skipped.

CA-180764 & CA-180765: Fix UninstallMSIs() bugs

---

src/xenprep/XenPrepSupport.cs

Server class windows doesn't have restore points, so we can't create them

[CA-181656] Don't fail if we can't create a restore point

---

src/installwizard/InstallWizard/Support.cs
src/installwizard/UIEvent/UIEvent.csproj
src/xenprep/XenPrep.cs
src/xenprep/XenPrepSupport.cs

And again after upgrade, because MSI update recreates them
And cope with new driver names

CA-180293 : Remove Xenvif class registry entries prior to upgrade

---

manifestspecific.py

Update to XenVif#57 (not-WHQLed)

---

src/InstallAgent/InstallAgent.sln
src/InstallAgent/InstallAgent/DIFx.cs
src/InstallAgent/InstallAgent/HardwareDevice.cs
src/InstallAgent/InstallAgent/InstallAgent.Designer.cs
src/InstallAgent/InstallAgent/InstallAgent.cs
src/InstallAgent/InstallAgent/InstallAgent.csproj
src/InstallAgent/InstallAgent/InstallerState.cs
src/InstallAgent/InstallAgent/Kernel32.cs
src/InstallAgent/InstallAgent/Msi.cs
src/InstallAgent/InstallAgent/Program.cs
src/InstallAgent/InstallAgent/ProjectInstaller.Designer.cs
src/InstallAgent/InstallAgent/ProjectInstaller.cs
src/InstallAgent/InstallAgent/ProjectInstaller.resx
src/InstallAgent/InstallAgent/Properties/AssemblyInfo.cs
src/InstallAgent/InstallAgent/SetupApi.cs
src/InstallAgent/InstallAgent/SimpleParse.cs
src/InstallAgent/InstallAgent/TimeDateTraceListener.cs
src/InstallAgent/InstallAgent/WinVersion.cs

CP-14471: [SOXP] Create InstallAgent Windows service
CP-14475: [SOXP] Implement logging mechanism
CP-14476: [SOXP] Design crude InstallAgent API and workflow

InstallAgent: Initial commit

---

src/InstallAgent/SetupApi.cs

Imported some functions from setupapi.dll
Created the appropriate enums and structs
to be used with the functions.

class SetupApi changes

---

manifestspecific.py

Update to tag XenVbd 8.1.0-rc4
Update to tag XenIface 8.1.0-rc4

Update: XenVbd #115, XenIface #20

---

manifestspecific.py

Update to XenVif 57 (WHQL)

---

manifestspecific.py
src/netsetlib/registry.h
src/netsetlib/restore.cpp
src/netsetlib/save.cpp

Update xenguestagent to 157
Backport 119a504edd7350f697ca18b26478df63ac37c0f9

CA-184345 & CA-178239

---

build.py

Creedence TOOLS_HOTFIX_NUMBER should be 20400

Creedence TOOLS_HOTFIX_NUMBER

---

src/InstallAgent/InstallAgent.Designer.cs
src/agent/managementagent.wxs

Correct service name: 'InstallAgent' 

---

manifestspecific.py

xeniface #25

---

manifestspecific.py

CA-196881: Update Guest Agent

---

src/diagnostics/CHANGELOG.txt
src/diagnostics/xtbugtool.bat

Initial submission of diagnostic tool
Committed-by:blaine.anaya@citrix.com

Diagnostic Tool Added

---

build.py
src/agent/citrixguestagent.wxs
src/agent/managementagent.wxs

Ignores return value of register/deregister updater task

Rename XenUpdater -> ManagementAgentUpdater in citrixguestagent.msi

---

manifestspecific.py

* Extra logging
* Limit download size
* Increase check period to 7 days
* Branding fixes

Update to guestagent #169

---

src/PVDriversRemoval/PVDriversPurge.cs

When cleaning system of < 8.x drivers, check also for C000 devs

---

manifestspecific.py

Update to guestagent 170

---

manifestspecific.py

XenGuestAgent 175

---

src/InstallAgent/InstallAgent.cs

CA-200585: Assume InstallAgent failed if max reboots reached

---

manifestspecific.py

* Fix XenStoreItem.Exists in Updater

XenGuestAgent 176

---

manifestspecific.py

* Branding path fixes for updater

Add XenGuestAgent 177

---

manifestspecific.py

* CP-15241: win-guestagent set static ip set according to xenstore key
* CA-201219 : join threads & log on shutdown

XenGuestAgent 179

---

src/setup/Setup.cpp

WriteCurrentUserSidToRegistry() now tries to open the InstallAgent
registry key (and not create it). If it fails, we conclude that
we are uninstalling, and skip calling waitForStatus() altogether
When installing:
- The key is created in the InstallAgent static constructor,
which is created before the OnStart() method is called
- MSI installer waits until OnStart() returns to return itself
- It is guaranteed that the key exists after installMsi()
- WriteCurrentUserSidToRegistry() returns TRUE
When uninstalling:
- The MSI installer removes all registry keys
- After installMsi() returns, WriteCurrentUserSidToRegistry()
will return FALSE
Also:
- Fixed formatting
- Do not retry opening registry keys; failure is an error
- Moved query for PV-Tools-on-first-run before the 'for' loop
- If …

CA-204485: Setup.exe identifies install/uninstall and acts accordingly

---

manifestspecific.py

CA-203818: Remove limit of set IP twice

XenGuestAgent 181

---

proj/InstallWizard.sln
src/ManagementAgentCA/DllMain.cpp
src/ManagementAgentCA/ManagementAgentCA.def
src/ManagementAgentCA/ManagementAgentCA.filters
src/ManagementAgentCA/ManagementAgentCA.vcxproj
src/ManagementAgentCA/SetInitiatorSidProperty.cpp
src/ManagementAgentCA/stdafx.cpp
src/ManagementAgentCA/stdafx.h
src/ManagementAgentCA/targetver.h
src/agent/managementagent.wxs
src/setup/Setup.cpp

Created C++ Custom Action project (dll file) to set the
[INITIATORSID] property in managementaganet.wxs.
We then use the property to write the value to the registry
at the same time with [REBOOTOPTION] and [INSTALLMODE].
This functionality has been removed from Setup.exe.

CA-205114: Create WiX Custom Action project to set Initiator Sid

---

manifestspecific.py

Reverts xenserver/win-installer#342

Revert "xen guest agent 184"

---

build.py

Reverts xenserver/win-installer#349

Revert "CP-16426 : provide a 'future version' msi for test purposes - sign te…"

---

src/branding/branding.py

Reverts xenserver/win-installer#350

Revert "CP-16426 : provide a 'future version' msi for test purposes - need to…"

---

build.py

Reverts xenserver/win-installer#347

Revert "CP-16426 : provide a 'future version' msi for test purposes - 2"

---

manifestspecific.py

* xenbus (8.1.0.63)
* xeniface (8.1.0.26)
* xenvif (8.1.0.62)
* xennet (8.1.0.42)
* xenvbd (8.1.0.130)

Add WHQLed drivers

---

src/agent/managementagent.wxs

CA-206454 : Stop trying to remove guest agent service before it is stopped

---

manifestspecific.py

Reverts xenserver/win-installer#364

Revert "Revert for to #771 build number update"

---

manifestspecific.py

* Parse Architecture from updates.tsv correctly

Update to guestagent 198

---

src/InstallAgent/InstallAgent.cs
src/InstallAgent/State/VM.cs

even if it is not required for the install to complete.

CA-212163: /forcerestart should reboot at least once

---

manifestspecific.py

CA-215212 CA-209069: XENIFACE 30

CA-215243: XENVBD 132

---

manifestspecific.py

* Add missing comma in inf file

Update to xenbus 8.1.1.64

---

manifestspecific.py

CA-219160 CA-219161 : Take note of xenstore when installing updates

XenGuestAgent 207

---

src/InstallAgent/InstallAgent.cs

There are some rare cases, where after the first InstallAgent-initiated
reboot, registry keys/values are missing.
2 possible fixes are:
- try to read 'InstallMode' up to 10 times, with a 5 sec interval
inbetween the tries
- Open the root InstallAgent registry key and explicitly flush it
before rebooting

CA-220461: Possible fix for missing 'InstallMode' registry value

---

manifestspecific.py

Update to XenNet 8.1.0.42 (WHQL inc Svr2016)

---

manifestspecific.py

CA-224610 : Improve hygine of xenbus_store printf api calls

Xeniface #64

---

manifestspecific.py

Reverts xenserver/win-installer#443 puts 2016 drivers back

UPD:32 Revert "UPD-31 : revert to pre-2016 whqled drivers"

---

manifestspecific.py

Reverts xenserver/win-installer#444

Revert "UPD:32 Revert "UPD-31 : revert to pre-2016 whqled drivers""

---

manifestspecific.py

Reverts xenserver/win-installer#453

Revert "Revert "UPD:32 Revert "UPD-31 : revert to pre-2016 whqled drivers"""

---

manifestspecific.py

Dont close/reopen ring during reset

Update to XenVbd 150

---

manifestspecific.py

Update XenVbd #156

---

src/agent/citrixguestagent.wxs

CA-216091 : Ensure our services depend on crypto service

---

manifestspecific.py

Reverts xenserver/win-installer#454 to UPD-31

Revert "Revert "Revert "UPD:32 Revert "UPD-31 : revert to pre-2016 whqled drivers""""

---

manifestspecific.py

Reverts xenserver/win-installer#459

Revert "Revert "Revert "Revert "UPD:32 Revert "UPD-31 : revert to pre-2016 whqled drivers"""""

---

manifestspecific.py

Update XenNet (64) and XenVif (103)

---

manifestspecific.py

XenGuestAgent 214

---

manifestspecific.py
src/agent/managementagent.wxs
src/branding/branding.py
src/setup/Setup.cpp

UI Support For turning on and off identification using with autoupdate
User agent changing for test purposes

Car 2351 uuid

---

src/HelperFunctions/Helpers.cs
src/InstallAgent/InstallAgent.cs
src/InstallAgent/PVDevice/PVDevice.cs
src/InstallAgent/PVDevice/XenBus.cs
src/InstallAgent/PVDevice/XenIface.cs
src/InstallAgent/PVDevice/XenVbd.cs
src/InstallAgent/PVDevice/XenVif.cs
src/PInvokeWrap/SetupApi.cs

the driver is not already there.
If the driver is already there, do not force install it
(unless it has been disabled)
Also ensure xenagent is started afer xeniface is restarted
(because we turn it off on an uninstall)

Only install drivers to driverstore if

---

manifestspecific.py

CA-248924 : Remove excessive logging after resume

Xeniface 8.2.1.100

---

src/HelperFunctions/Helpers.cs

There is a chance that when 'HelperFunctions.Helpers.ServiceRestart()'
is called, the service to restart is not in the 'Running' state. This
resulted in the service not being asked to stop, and the InstallAgent
to wait indefinitely until it's stopped.
- Call 'Stop()' if service is in any state except 'Stopped' or
'StopPending'
- Removed 'WaitForStatus()' call; instead check the service's status
every second and log it

CA-248538: Fix deadlock while restarting system services

---

manifestspecific.py

Prevent driver handling Irps before Fdo is created

XenBus 104

---

manifestspecific.py

CA-166179 : Manually reset suspend and shutdown event

XenIface 102

---

manifestspecific.py

bump xenbus version

---

manifestspecific.py

bumpup xenbus version

---

manifestspecific.py

bump up xenbus version to 113

---

src/InstallAgent/InstallAgent.cs
src/InstallAgent/InstallAgent.csproj
src/InstallAgent/PVDevice/PVDevice.cs
src/InstallAgent/PVDevice/XenCons.cs
src/InstallAgent/State/Installer.cs

Add XenCons to InstallAgent

---

manifestspecific.py

Update to xenguestagent 254

---

manifestspecific.py

CA-264903 : Add support for  a message based protocol

XenGuestAgent 255

---

build.py
manifestspecific-inspur.py
sign.vbs
src/branding/branding.py

backport the enhanced build to honolulu

Backport honolulu

---

build.py
manifestspecific-inspur.py
sign.vbs
src/branding/branding.py

backport  the enhanced build to falcon

Falcon backport

---

src/HelperFunctions/Helpers.cs
src/InstallAgent/PVDevice/PVDevice.cs
src/InstallAgent/State/VM.cs

xenrt job: 189684 
1896868~~1896874  1896876 1896877 1896879~1896883

CA-263466: Cannot upgrade drivers when system shutdown during upgrading

---

manifestspecific-inspur.py
manifestspecific.py

CA-248477 Advertise feature-shutdown for Dundee

XenIface 103

---

src/InstallAgent/PVDevice/PVDevice.cs
src/InstallAgent/PVDevice/XenBus.cs
src/InstallAgent/PVDevice/XenIface.cs
src/InstallAgent/PVDevice/XenVbd.cs
src/InstallAgent/PVDevice/XenVif.cs

xenrt job id:
1909726 -- 1909735

CA-269002: Keep restall xenvif and fail

---

manifestspecific.py

Update XenVbd to #203

---

manifestspecific.py

Update XenNet to #102

---

manifestspecific-inspur.py

Use reselled signed windows drivers

---

manifestspecific.py

Update WHQLed xenvbd to #203

---

manifestspecific.py

Update xenbus to 117 WHQLed

---

manifestspecific-inspur.py
manifestspecific.py

Resolve WHQL issue due to uninitialized field in MDL

Xenvif 155
