xenserver/win-installer

manifestspecific.py
CP-10514 : Watch RDP Status in Windows PV tool
CP-10490 : puncture firewall when enabling RDP
CA-150831 : Do not cache Win32_TerminalService Setting WMI Object
CA-151657: Increase speed of dpriv to guest agent clipboard copying
=> win-guestagent #126

manifestspecific.py
This is the introduction of the 8.0 driver stream which
derive from the xen project and can be located at
http://xenbits.xen.org/gitweb/
Our base 8.0 drivers are
xenbus 12
xenvif 5
xennet 4
xeniface 3
xenvbd 9
Please make changes to these drivers, following the
process documented at
http://www.xenproject.org/developers/teams/windows-pv-drivers.html
We continue to use
xenguestagent 127
and
xenvss 16
Which derive from the XenServer github repositories, and continue
to follow a github pull-request based workflow
=> [CP-10562] Moving to patchqueue based drivers

src/installwizard/InstallWizard/InstallService.cs, src/installwizard/InstallWizard/Support.cs
Refactors setupapi functions to move them into a module of their own
Detects if a bus device's children are not available using CM_Get_DevNode_Status
Detects if all current installs have finished using CMP_WaitNoPendingInstallEvents
Clarified the 'servicesrunning' function
We no longer need to rely on reenumerating the bus to try to determine if all install events have finished
=> [CA-159586] Wait for all installs to finish before rebooting

src/drivers/citrixxendrivers.wxs, src/installwizard/installwizard.wxs
Unfortunately, current Win10 previews report its VersionNt as 603 (win 8.1)
so we install on 8.1 and above, and have altered some text strings in the
installers to say "Windows 10 Preview" very clearly
=> CP-12176 : Win10 Preview should only install on Windows 10

manifestspecific.py
[XenVbd] Rebase: f182c908f29fa87887b39950d289c8af4ae512f5
Rebase to upstream and clear patch queue of applied patches
* Account for rewinding requests master
* Fix device relations in xendisk filter
* Fix ASSERT
* Fix ASSERT, s/Recieved/Received
* Calculate size of DEVICE_RELATIONS
=> XenVbd #94

src/netsetlib/registry.cpp
So reduce level of access to the registry needed to allow netsettings
to run
=> CA-167589 :  Windows installer doesn't elevate all actions

src/installwizard/InstallWizard/Support.cs
We want to switch to emulated for boot, so that if xenvbd/xenbus
compatability breaks, we can still boot up
=> CA-176746 : Do not unplug disk when upgrading xenvbd

src/installwizard/InstallWizard/Support.cs
This is needed in case the NICs have been set to bootstart by PVS
=> CA-176746 : Don't unplug NICs on upgrade

src/installwizard/InstallWizard/Support.cs
=> ca-176746 : Once we've unplugged net drivers, xenvif doesn't need to

build.py, proj/XenPrep.sln, src/xenprep/Progress.Designer.cs, src/xenprep/Progress.cs, src/xenprep/Progress.resx, src/xenprep/XenPrep.cs, src/xenprep/XenPrepSupport.cs, src/xenprep/Xenprep.csproj
Currently a stub version of the xenprep utility which does nothing useful
It is included in installer/builds (and thus in the output collected
in the installer tar file, but not used beyond that point)
The intent is that all useful functionality will go into XenPrepSupport.cs,
which may also be included by other tasks that require the same functionality
(in particular the installwizard)
=> CP-13459 : introduce xenprep into installer build

src/xenprep/XenPrep.cs, src/xenprep/XenPrepSupport.cs
Lock all optical drives at the start of XenPrep;
Unlock them in the end and eject them.
=> CP-13738 & CP-13460: Lock, Unlock and Eject Optical Discs

src/xenprep/XenPrepSupport.cs
Fix bug that caused DontBootStartDrivers() to not open
any existing driver subkey.
=> CA-180772: XenPrep DontBootStartDrivers() not working correctly

src/xenprep/XenPrepSupport.cs
Cleanup PV driver subkeys in 'HKLM\SYSTEM\CurrentControlSet\Services'
=> CA-180699: XenPrep does not remove driver service details

src/xenprep/Xenprep.csproj, src/xenprep/Xenprep.exe.config
Added config file that enables XenPrep to run on .NET >= 4.0.
=> CA-180819: Make XenPrep run on .NET >= 4.0

src/installwizard/installwizard.wxs, src/xenprep/XenPrepSupport.cs
The way this works is:
We have to include both the 64 bit and the 32 bit difxapi.dll for .net's sake
So we give them different names
Then use object abstraction so only one of the 32 or 64 bit interfaces are visible to the code.
=> CA-183597 : incorporate DifXAPI.dll into installwizard

src/installwizard/InstallWizard/Support.cs
Reverts xenserver/win-installer#221
This change was incorrect - we want to install if we have an empty driver name, not block the install.
=> Revert "CA-184369 : Don't block install if we've removed driver details"

manifestspecific.py, src/agent/managementagent.wxs
If .NET 3.5 was installed, InstallAgent.exe.config was not being copied
to the XenTools folder. That file has information about the location of
BrandSupport.dll.
=> CA-196843: Always copy .exe.config files to XenTools dir

src/agent/managementagent.wxs
Remove stale component. Management Agent msi does not build
=> Remove component 'dotnetfouragent'

src/PVDriversRemoval/PVDriversPurge.cs
If legacy tools are being used, an extra registry entry is
needed to make the drivers not bootstart after reboot
=> CA-197641: If legacy tools present, write registry entry

src/HelperFunctions/Helpers.cs, src/InstallAgent/InstallAgent.cs, src/InstallAgent/PVDevice/PVDevice.cs, src/InstallAgent/PVDevice/XenVif.cs, src/PVDriversRemoval/PVDriversPurge.cs
It appears windows can 'forget' a driver is bootstart - so this ensures windows is told our bootstart drivers are also boot start.
We check drivers which are not bootstart in case a user (such as PVS) has set them to start at boot time
=> CP-14538:  Ensure drivers set to bootstart start at boot time

src/InstallAgent/InstallAgent.cs
Reduce the waiting time from 20 minutes to 10 before an
auto-reboot, if there was a driver installing before
InstallAgent's first run
=> Change "wait for drivers to install" timeout

build.py, src/HelperFunctions/Helpers.cs, src/InstallAgent/InstallAgent.cs, src/PInvokeWrap/AdvApi32.cs, src/PInvokeWrap/Kernel32.cs, src/PInvokeWrap/WinError.cs, src/PInvokeWrap/WtsApi32.cs, src/setup/Setup.cpp
Present a MessageBox to the user who initiated the PV Tools installer
with a success/failure message the next time they log on after the
installer has finished.
This works as follows:
- Setup.exe gets the currently logged on user's SID and
writes it under the 'InstallAgent' registry key
- When the InstallAgent has finished all work it:
- Enumerates all sessions
- If a session is active, compares the logged on user's
SID with the initiator's SID
- If they match, a message is sent to that user to inform
them of the status of the install and the InstallAgent
is put into 'Manual' startup mode
- If not, a check is performed every 15 seconds until the
initiator logs in and gets the message
Other changes:
- Escape backslashes in setup branding.h
- Setup.exe prompts the user for a reboot only in …
=> CP-16417: Inform Setup.exe initiator about InstallAgent outcome

src/agent/managementagent.wxs
When installing Management Agent, write the 'InstallMode'
value to the InstallAgent registry key:
- Normal install => 'InstallMode' = FULL
- /quiet => 'InstallMode' = QUIET
- /passive => 'InstallMode' = PASSIVE
=> CP-16527: [ManagementAgent] Write 'InstallMode' to Registry

src/InstallAgent/InstallAgent.cs, src/InstallAgent/PVDevice/XenBus.cs, src/InstallAgent/State/VM.cs
- Added 'InstallMode Enum'/'installMode' static variable;
Installer initiator gets notified only if installMode == FULL
- 'InstallStatus' is now an Enum
- Created InstallerDone() and InstallerReboot(); tidied up
InstallThreadHandler()
- Added BlockUntilInitiatorNotified()
- Removed VM.rebootNeeded + Set* Get*; superseeded by
'InstallStatus.NeedsReboot'
- Added comments on entrance/exit of static constructors
=> Workflow fixing and polishing

src/HelperFunctions/Helpers.cs, src/InstallAgent/InstallAgent.cs, src/InstallAgent/State/Installer.cs
This behaviour is only seen on the driver upgrade case. After the first
reboot, InstallAgent is able to read the state of the installer from
the registry and continues where it left off (uninstalling the MSIs).
However, uninstalling 'Citrix XenTools Installer' takes ~10 minutes
to complete. After 'UninstallMSIs()' returns, we try to set the
'MSIsUninstalled' flag to the registry and an exception is raised
because it cannot be opened.
This commit comprises 2 possible fixes:
- Wait until the '_MSIExecute' mutex is available/free before
rebooting (if AUTOREBOOT)
- Enclose the install state reg key in a 'using' statement in the
'Installer' static constructor
=> CA-206396: InstallAgent raises exception on opening reg key

src/HelperFunctions/Helpers.cs
If newer drivers are installed for a hardware device,
DiInstallDriver() returns FALSE and sets Last Error
to ERROR_NO_MORE_ITEMS.
InstallDriver() is changed to not throw an exception when
DiInstallDriver() returns FALSE, but to check the Last
Error; if different than 0 or 259, throw.
=> CA-212319: Do not fail if newer drivers already installed

src/HelperFunctions/Helpers.cs, src/InstallAgent/PVDevice/XenIface.cs
Following a reinstall of the same version of xeniface, the lite agent
fails to notice its WMI agent is broken.  As a workaround, having
installed Xeniface we restart the xenlite service.
When we move to a later lite agent which uses IOCTLs rather than
WMI, we can remove this workaround
=> CA-213907 : ensure lite agent WMI connection is reestablished

src/HelperFunctions/Helpers.cs, src/InstallAgent/InstallAgent.cs, src/PInvokeWrap/AdvApi32.cs, src/PInvokeWrap/WtsApi32.cs
We have to be careful passing an IntPtr.Zero into a pinvoked function
that wants to overwrite that memory with a real address
WTSQueryUserToken needs the privilege SE_TCB_NAME
If we can't find the user for a session, ignore it - it might not
be our session - and we can fail later when we don't find ourself
public enum MB should be a uint, not a ulong
WTSQueryUserToken takes a Uint32 sessionId - not a ulong
=> CA-218258: Fix installer succeeded dialog display

src/InstallAgent/InstallAgent.cs
functioning
As part of checking if xeniface is functioning (in the pre-xenagent
era only) the lite agent is restarted to ensure it reconnects via
wmi.  This was lost in the refactoring needed in the revised
mgmt agent merge
=> CA-225008 : Do not reboot until we've checked if xeniface is

src/HelperFunctions/Helpers.cs
A 'ServiceController' object can be created with a non-existent
service. If this is the case, a call to the 'CanStop()' member
method of the object will throw an 'InvalidOperationException'.
Put the 'CanStop()' check in a try/catch block.
Also, add a call to 'Refresh()' before we check the 'Status'
field and replace the generic 'Exception' with 'Win32Exception',
since this is the only exception other than 'InvalidOperationException'
that 'Start()'/'Stop()' can throw.
=> CA-258622: Fix unhandled exception in Helpers.ServiceRestart()

manifestspecific.py
Rebranded drivers check correct name to determine if they can install
=> CA-255936 : Add xenbus 113 to honolulu

manifestspecific.py
Importing from upstream e4a153d3741b7cfd5c3389eafa94df2a33eed80c
Fix SDV
Update version to 8.2.1
Request reboot keys should be volatile
Clean up use of MmGetSystemAddressForMdlSafe()
Don't try to __FreePages() with local copy of MDL
Remove the explicit ExFreePool(Mdl) in TransmitterBuffe...
Fix memory leak in __FreePage()
=> Xenvif 152

build.py, manifestspecific.py
Pull in XenCons (backported build of 9.0 to vs2012) and XenBus
(backported build of 9.0 to vs2012)
=> [REQ-330] Add XenCons driver and updated XenBus

manifestspecific.py
* Disables xenbus default console logging
* Disables xencons default tty execution
=> Update to XenBus 115, XenCons 7

manifestspecific.py, src/agent/managementagent.wxs
- Packaged 'XenConsoleComm.dll' and 'IXenConsoleComm.dll' in the
installer
- Add registry entry for 'XenConsoleComm.dll' path under
'HKLM\SOFTWARE\Citrix\XenTools\XenConsoleComm\DllPath'
=> Add 'XenConsoleComm.dll' and 'IXenConsoleComm.dll'

manifestspecific-inspur.py, manifestspecific.py
UPD-108 : XENVIF 8.2.1.152
CA-251602 : Xenbus monitor not removing reboot key
UPD-109 : XENIFACE 8.2.1.102
CA-248924 : Excessive logging in windows after resuming from suspend
UPD-110 : XENVBD 8.2.1.158
CA-237752 Windows 7 VM wedged in reboot loop (PdoReset loop)
CA-257867 : SCTX-2567 : XENVBD caused VM hang
=> CP-23143 Merge HFX Hokulea Fixes
